spring.application.name=url-shortener

# =====================
# DATABASE CONFIG
# =====================
spring.datasource.url=jdbc:postgresql://localhost:5433/url_shortener_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================
# JPA CONFIG
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =====================
# SERVER CONFIG
# =====================
server.port=8080

# =====================
# APP CONFIG
# =====================
app.base-url=http://localhost:8080

# =====================
# SWAGGER CONFIG
# =====================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true